name: trigger jenkins job
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "http://jenkins.kudernatsch.at"
        user: "admin"
        token: ${{ secrets.TOKEN }}
        job: "spacerobots, spacerobots_2"
